server:
  port: 5000

spring:
  jpa:    
    show-sql: true

logging:
  level:
    root: INFO    
    # org.hibernate.SQL: debug

# spring:
#   session:
#     store-type: jdbc
#     initialize-schema: always
