server:
  port: 8080
# spring:
#   datasource:
#     url: jdbc:mysql://localhost:3306/mydatabase
#     username: myusername
#     password: mypassword
#     driver-class-name: com.mysql.jdbc.Driver
#   jpa:
#     hibernate:
#       ddl-auto: update
#     show-sql: true
logging:
  level:
    root: INFO
    com.example: DEBUG

server:
  servlet:
    context-path: /api/v1
