package com.player.props.util.mappers;

import com.player.props.dao.FullName;
import com.player.props.dao.PlayerPropsFactEntity;
import com.player.props.model.response.PlayerStatsResponse;

public class PlayerStatsEntityToResponseMapper {

  static public PlayerStatsResponse map(PlayerPropsFactEntity entity) {
    return PlayerStatsResponse.builder()
        .player_game_id(entity.getPlayer_game_id())
        .game_id(entity.getGame_id())
        .date(entity.getDate())
        .player_id(entity.getPlayer_id())
        .first_name(entity.getFullName().getFirstName())
        .last_name(entity.getFullName().getLastName())
        .position(entity.getPosition())
        .team_id(entity.getTeam_id())
        .abbreviation(entity.getAbbreviation())
        .city(entity.getCity())
        .conference(entity.getConference())
        .division(entity.getDivision())
        .full_name(entity.getFull_name())
        .pts(entity.getPts())
        .rbs(entity.getRbs())
        .asts(entity.getAsts())
        .stls(entity.getStls())
        .blks(entity.getBlks())
        .tos(entity.getTos())
        .fg3m(entity.getFg3m())
        .fg3a(entity.getFg3a())
        .fg3_pct(entity.getFg3_pct())
        .fgm(entity.getFgm())
        .fga(entity.getFga())
        .fg_pct(entity.getFg_pct())
        .ftm(entity.getFtm())
        .fta(entity.getFta())
        .ft_pct(entity.getFt_pct())
        .oreb(entity.getOreb())
        .dreb(entity.getDreb())
        .pf(entity.getPf())
        .min(entity.getMin())
        .opposing_team_full_name(entity.getOpposing_team_full_name())
        .opposing_team_id(entity.getOpposing_team_id())
        .postseason(entity.isPostseason())
        .season(entity.getSeason())
        .build();
  }

  static public PlayerPropsFactEntity responseToEntity(PlayerStatsResponse response) {
    return PlayerPropsFactEntity.builder()
        .player_game_id(response.getPlayer_game_id())
        .game_id(response.getGame_id())
        .date(response.getDate())
        .player_id(response.getPlayer_id())
        .fullName(FullName.builder()
            .firstName(response.getFirst_name())
            .lastName(response.getLast_name())
            .build())
        .full_name(response.getFull_name())
        .position(response.getPosition())
        .team_id(response.getTeam_id())
        .abbreviation(response.getAbbreviation())
        .city(response.getCity())
        .conference(response.getConference())
        .division(response.getDivision())
        .full_name(response.getFull_name())
        .pts(response.getPts())
        .rbs(response.getRbs())
        .asts(response.getAsts())
        .stls(response.getStls())
        .blks(response.getBlks())
        .tos(response.getTos())
        .fg3m(response.getFg3m())
        .fg3a(response.getFg3a())
        .fg3_pct(response.getFg3_pct())
        .fgm(response.getFgm())
        .fga(response.getFga())
        .fg_pct(response.getFg_pct())
        .ftm(response.getFtm())
        .fta(response.getFta())
        .ft_pct(response.getFt_pct())
        .oreb(response.getOreb())
        .dreb(response.getDreb())
        .pf(response.getPf())
        .min(response.getMin())
        .opposing_team_full_name(response.getOpposing_team_full_name())
        .opposing_team_id(response.getOpposing_team_id())
        .postseason(response.isPostseason())
        .season(response.getSeason())
        .build();
  }
}